version: '3'
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: kvrae/kaddem:${BUILD_NUMBER}
    restart: on-failure
    ports:
      - "8089:8089"

    depends_on:
      - mysqldb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
