version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application Service
  spring-app:
    image: kvrae/kaddem:${BUILD_NUMBER}
    restart: on-failure
    ports:
      - "6868:8089"

    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db: